<?php

namespace App\Services;

use Firebase\JWT\JWT;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;

class OnlyOfficeService
{
    public function buildConfig($attachment, $user, string $callbackUrl, string $downloadUrl, string $title, string $mode = 'edit'): array
    {
        $ext = pathinfo($attachment->file_name, PATHINFO_EXTENSION);
        $docType = $this->getDocumentType($ext);
        $secret = config('onlyoffice.secret');

        $key = md5($attachment->id . '_' . $attachment->updated_at->timestamp);

        $config = [
            'document' => [
                'fileType' => strtolower($ext),
                'key' => $key,
                'title' => $title,
                'url' => $downloadUrl,
                'permissions' => [
                    'edit' => $mode === 'edit',
                    'download' => true,
                ],
            ],
            'documentType' => $docType,
            'editorConfig' => [
                'callbackUrl' => $callbackUrl,
                'user' => [
                    'id' => (string) $user->id,
                    'name' => $user->name,
                ],
                'mode' => $mode,
                'lang' => app()->getLocale(),
                'customization' => [
                    'forcesave' => true,
                    'autosave' => true,
                ],
            ]
        ];

        if (!empty($secret)) {
            $config['token'] = JWT::encode($config, $secret, 'HS256');
        }

        return $config;
    }

    public function handleCallback(Request $request, $attachment, callable $logActivity)
    {
        $body = $request->json()->all();

        $secret = config('onlyoffice.secret');
        if (!empty($secret)) {
            $token = $body['token'] ?? $request->header('Authorization') ?? $request->header('X-CDES-JWT');
            
            if (!$token) {
                Log::warning("[OnlyOffice] Invalid callback received: No token provided.");
                return ['error' => 1, 'message' => 'Authentication required'];
            }

            try {
                $jwtStr = Str::startsWith($token, 'Bearer ') ? substr($token, 7) : $token;
                JWT::decode($jwtStr, new \Firebase\JWT\Key($secret, 'HS256'));
            } catch (\Exception $e) {
                Log::error("[OnlyOffice] JWT Decoded fail: " . $e->getMessage());
                return ['error' => 1, 'message' => 'Invalid token signature'];
            }
        }

        $status = (int) ($body['status'] ?? 0);

        if ($status === 2 || $status === 6) {
            $downloadUri = $body['url'] ?? null;
            if (!$downloadUri) {
                Log::error("[OnlyOffice] Status 2 but no download URL received for Attachment {$attachment->id}");
                return ['error' => 1, 'message' => 'No download URL provided by editor'];
            }

            try {
                $internalServerUrl = config('onlyoffice.internal_server_url');
                if (!empty($internalServerUrl)) {
                    $publicServerUrl = rtrim(config('onlyoffice.url'), '/');
                    $downloadUri = str_replace($publicServerUrl, rtrim($internalServerUrl, '/'), $downloadUri);
                }

                $newFileContent = file_get_contents($downloadUri);
                if ($newFileContent === false) {
                    throw new \Exception("Could not retrieve file from {$downloadUri}");
                }

                Storage::disk('public')->put($attachment->file_path, $newFileContent);
                
                $attachment->update([
                    'file_size' => strlen($newFileContent),
                    'updated_at' => now()
                ]);

                Log::info("[OnlyOffice] Attachment ID {$attachment->id} updated successfully via callback.");
                
                $userId = $body['users'][0] ?? null;
                $logActivity($userId);

            } catch (\Exception $e) {
                Log::error("[OnlyOffice] Error updating file for Attachment {$attachment->id}: " . $e->getMessage());
                return ['error' => 1, 'message' => 'Internal write failure'];
            }
        }

        return ['error' => 0];
    }

    public function minimalDocx(): string
    {
        return base64_decode('UEsDBBQABgAIAAAAIQDiq6y32gAAACkBAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslEsOwyAMRfdI3CFSdx111VWEHICiBoQwsH9v3xS1aNUui2xshH0+9sZ6c5sNxE5sLHgpS1EMjrEWuJTwWe7LF1HkIJbWODh4CSeEsN7dXM0X2yCCztiFlGzIT1HqR6wXbN2I2oWjkT0n0+y8mE+HMTnK1s1s2Wk6l8aBf9Bf1oX5y5rXqS6X72d5zK4xHnQ0x8Lg8+G2z17XvT8Z8wEwA/fI5eD9vA43t34AAAD//wMAUEsDBBQABgAIAAAAIQAekRq38wAAAE4CAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJLBasMwDEDvg/2D0b2V1l1GKNlbCmM32m2vIRzbSGyNjcZJ9++zM2R0h7IeGjzJ09PTaL2eXWMU78i2DlrBpqwg0Zq2622F7+vH6g1EEkNXjB1Y4Ygc2uXpafWCE6e8p2lPJSKhSqwYYu6fWk4xN1xGqR9sI2sOceakjDrmE6tPdk3jWZZLjn2A2tPZqiu8bXoDMW81eB074+vY0p84Rz7iM2fHk7+j/Bik0G8q1oVq4vL0F2qI2+m0k4q4JbK2VpD6O2n75Gg4E7fP6d9F2Ue/AAAA//8DAFBLAwQUAAYACAAAACEAX4/z9v8BAADvBAAAHAAIAXdvcmQvX3JlbHMvZG9jdW1lbnQueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsVMFOwzAMvSPxH6HcmdZpCCGldkLioB2QOPEB1sRpjD6SNpP29yRthwaTCNchK/b7LHu+vt5uz3rAHti40nLGi+UCA5/w1pa1nPHH8ur8hgHPIjBtrYBn3MDG2/r6anzBEeO6rA5HFRHnB2fcsd5XyBwNnQpxdME2t0fI/d2qgHnmO11o2H/Yk0xmyyW/Qe1hPdkzXl1fW+hP1s204s+tZ69x1bWp0U9sK/pINnBWehA/Uv84zP1U01R+B0411B3i4r21lU2yV1X8P70Gz9k2NqM/Qn2gVqGq0a3T3gJ1Z2v7oH1x68Yg1G1q+mD46e9L7W+U809eAAAA//8DAFBLAwQUAAYACAAAACEA2S+12sIAAAAqAQAAEQAAAHdvcmQvZG9jdW1lbnQueG1s8syszs1LzSlJLVKwUkguSS1yVnDXD3IMcvPXC3IM93LWC4oPdw1yDfAL8Q1y9/fUD3XydtMPAoo4K+Qn5qQWWxkYGJkoGBqYGJkYKBjpG5noBwEAAP//AwBQSwMEFAAGAAgAAAAhANmY/gS6AAAALwEAAA8AAAB3b3JkL3N0eWxlcy54bWzwzDsOgzAQBNDaC124S1tEhYIoRfk2RskPjM0iO0u+L9h2000X97GzN8vj9T1uV/GgN8bB4EGe8hSDAx042D7I57reXmPwIVs/nK0n2Rj7hA/22S33+xMAAP//AwBQSwUGAAAAAAUABQARAQAANwIAAAAA');
    }

    public function minimalXlsx(): string
    {
        return base64_decode('UEsDBBQABgAIAAAAIQDiq6y32gAAACkBAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslEsOwyAMRfdI3CFSdx111VWEHICiBoQwsH9v3xS1aNUui2xshH0+9sZ6c5sNxE5sLHgpS1EMjrEWuJTwWe7LF1HkIJbWODh4CSeEsN7dXM0X2yCCztiFlGzIT1HqR6wXbN2I2oWjkT0n0+y8mE+HMTnK1s1s2Wk6l8aBf9Bf1oX5y5rXqS6X72d5zK4xHnQ0x8Lg8+G2z17XvT8Z8wEwA/fI5eD9vA43t34AAAD//wMAUEsDBBQABgAIAAAAIQAekRq38wAAAE4CAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJLBasMwDEDvg/2D0b2V1l1GKNlbCmM32m2vIRzbSGyNjcZJ9++zM2R0h7IeGjzJ09PTaL2eXWMU78i2DlrBpqwg0Zq2622F7+vH6g1EEkNXjB1Y4Ygc2uXpafWCE6e8p2lPJSKhSqwYYu6fWk4xN1xGqR9sI2sOceakjDrmE6tPdk3jWZZLjn2A2tPZqiu8bXoDMW81eB074+vY0p84Rz7iM2fHk7+j/Bik0G8q1oVq4vL0F2qI2+m0k4q4JbK2VpD6O2n75Gg4E7fP6d9F2Ue/AAAA//8DAFBLAwQUAAYACAAAACEAlS17X/oBAABfAwAAGgAIAXhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJTBbsMwDEX3A/YPRO8dJ203QkjpNkLbrSj2AWKxTSzJ0Eh2m/bvS9N1g26nXdCDLJHv4yPpaL192kE+0bBxpWCcFxgY18JYW2mF18Pj4hkGz4zV1nLCClsMbLe7u+srTgw3ZbU9qYg4PymFY/WpwOZoxFWIswu2vj1CTndVBS0yj2TBYf9iDzKZLZf8hqrDerLHeHV5a2F6sm6mdX9uPfsbV12bGvXENqKHZIOWSs+SR+ofx9RPNUzlb+BQQ90gLl5a29gke1XFf9Nn8JSusRn1EXoOtQpVhW6dthaoL2bdj25duxEMddsaeWD06X/Vv5TySwAAAP//AwBQSwMEFAAGAAgAAAAhAGu09PfaAAAADQEAABMAAAB4bC93b3JrYm9vay54bWyMkD9rwzAQxfdDvwPRveWkTVrIVdsuge4t0A3G2nQSYw2W5bSp3z5xU2gpdOnxvXv34y2X28F0G2wINq4UzHMBgXEvjLWVgvu+nB7ngOc1q63lYMFN42w5Pz9F42K21A5Qo1WcFiwMh7WzLhXfU2XicMF2d/eQK/WkCqqyKCSY0eUj5bAsZ/xP1K5Wl7nB+5c3Bv6j212q/b71bC+uunY12oltpR9R2Kk+o4nUn8XUTTWWw99AT0PdI1582tp1R/aqgv+hZ/CcfW1X6I/QOdQq1Jro1mkboN7Y2jx0B27dGIR6T00/GT79I+X4AwAA//8DAFBLAwQUAAYACAAAACEAVtS2g+8AAABlAQAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbIQQzU7DMAy+I/EdIu8a2w2t6zRphCgHhDjwcK1Oam2SKE26vT1plxBCx/TzJ9vfq/vDaFfEIEytsCpzUAR1Q1prrMI/Py+LJxQpi01rDSqs0CEe1/f31cWsvoY2i0Z1WhUKnZ4Tz/OSB6G1WbN1kS7vT8nK0W2qQqubQjI4b18oJ2VZ8H9R+1rf5xbvb28M0qPbfanDofVsX111HWrSE9uKHpINWhZ9QhOpfxlT19VUzn8DDzXULeLFk7XNjezIVeXfQ8/QOdvepuiP0AdoFeoT3TntPdBXtjYP0s2tG4NQH6npg+Gn36X8AwAA//8DAFBLBQYAAAAABQAFAJEBAABZAgAAAAA=');
    }

    public function minimalPptx(): string
    {
        return base64_decode('UEsDBBQABgAIAAAAIQDiq6y32gAAACkBAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslEsOwyAMRfdI3CFSdx111VWEHICiBoQwsH9v3xS1aNUui2xshH0+9sZ6c5sNxE5sLHgpS1EMjrEWuJTwWe7LF1HkIJbWODh4CSeEsN7dXM0X2yCCztiFlGzIT1HqR6wXbN2I2oWjkT0n0+y8mE+HMTnK1s1s2Wk6l8aBf9Bf1oX5y5rXqS6X72d5zK4xHnQ0x8Lg8+G2z17XvT8Z8wEwA/fI5eD9vA43t34AAAD//wMAUEsDBBQABgAIAAAAIQAekRq38wAAAE4CAAALAAgCX3JlbHMvLnJlbHMgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArJLBasMwDEDvg/2D0b2V1l1GKNlbCmM32m2vIRzbSGyNjcZJ9++zM2R0h7IeGjzJ09PTaL2eXWMU78i2DlrBpqwg0Zq2622F7+vH6g1EEkNXjB1Y4Ygc2uXpafWCE6e8p2lPJSKhSqwYYu6fWk4xN1xGqR9sI2sOceakjDrmE6tPdk3jWZZLjn2A2tPZqiu8bXoDMW81eB074+vY0p84Rz7iM2fHk7+j/Bik0G8q1oVq4vL0F2qI2+m0k4q4JbK2VpD6O2n75Gg4E7fP6d9F2Ue/AAAA//8DAFBLAwQUAAYACAAAACEAhV0QyvkBAABBBAAAGgAIAXBwdC9fcmVscy9wcmVzZW50YXRpb24ueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsVU1vwjAMvUfiP0S+N2yDEEJqb0AcdhukTvwA1yROQ/SRtJm0fz9JWwcGExMuQ5T83mfbT19vt1ezYBdsXGk549kyw8AnvLVlLWf8sby6uGfAswhMWyvgGTew8ba+vlpfccS4LqvDQY+I84Mzbq33DTIHjU6FOHpgm9sT5P5utUCnzHe60rB/sSeZzJZLfoPaxXq0e7y6vrbQ76ybacSfa89u46prU6Mf2Fb0kWzgvPQgfqT+YZj6vqap/Awcaqi7xMV7aysbZ0+r+H/6DDym29mY/QnqBLUKVY0unbYWqDtb21vti1sXglD3qelnw0+/Uf6rkv8CAAD//wMAUEsDBBQABgAIAAAAIQB5z2g15gAAACMBAAAVAAAAcHB0L3ByZXNlbnRhdGlvbi54bWyMkM1qAzEMRfdDvwPRXU4TWhIybtoUumuhm4K1f/J41g9Jj2n37ys3hUIX3XrT1T169+V2u1m1m4wYhKk1zHMBgaAeSGutafjv5/V1DYUvW2tQYY0O+RGH2/v71cWMXoexiEYNWkUh7RrxPC95kNqaLTtX6XL+gqy2t2tVVHVVSLDg/S1lpCyX/F/UvnZ/bgn91xtDd7R7qHXctp6d1VVXoSY5safolGwwtOiRNER/nVNX1VSPPwMPNTRZ5MUHa5vtyJ5W8f/wCTzH1zaP/gndQ6lCbaE7p22Aumdr26A9ubVDEGozNf1r+OkPlPMfAAAA//8DAFBLAwQUAAYACAAAACEA78/HivsAAABNAQAAHgAAAHBwdC9zbGlkZXNDb250ZW50L3NsaWRlMS54bWyMkMFOwzAMhu9IvEOUd02TQAw1tROIBxgiDtZcO425T5omXdvbs7QdQmJwTL9/v/2zWp/W25U4CBtrvBbyYolAUPegtdeF/Hl5W1wi8GVrLRo06JD3cLm+vlqvxulnGBto9KJVrNL1GZk1kgdtrNlycJ0uz8fJam9f11VR1XUh0aINB+lHZbny/0Xt6nS1S/S/3hhmZ18X1U1tz97squtRk4mYKTonnY8Z3ZNz0R8TqqqaurF/kIYaWix68cHZZpWzj1X8P/0PnlPb3Rj9EfoIpQqtlB6cdgnUHVvbh+7JrRuFUIep6Zvh018op38AAAD//wMAUEsFBgAAAAAFAAUAkQEAAKACAAAAAA==');
    }

    public function getDocumentType($ext): ?string
    {
        $word = ['doc', 'docx', 'rtf', 'odt', 'txt'];
        $cell = ['xls', 'xlsx', 'ods', 'csv'];
        $slide = ['ppt', 'pptx', 'odp'];

        $e = strtolower($ext);

        if (in_array($e, $word)) return 'word';
        if (in_array($e, $cell)) return 'cell';
        if (in_array($e, $slide)) return 'slide';

        return null;
    }
}
